language: python
python:
#  - "2.6"
  - "2.7"
#  - "3.4"
#  - "3.5"
#  - "3.6"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libopenmpi-dev openmpi-bin

# command to install dependencies
install:
  - pip install .

# command to run tests
script: python -m unittest discover tests/

notifications:
  email:
      on_success: never # default: change
      on_failure: change # default: always
