language: python
python:
  - "2.7"
  - "3.6"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libopenmpi-dev openmpi-bin
  - sudo apt-get install r-base
  - wget https://cran.r-project.org/src/contrib/diptest_0.75-7.tar.gz
  - sudo R CMD INSTALL diptest_0.75-7.tar.gz

# command to install dependencies
install:
  - pip install . -v

# command to run tests
script: python -m unittest discover tests/

notifications:
  email:
      on_success: never # default: change
      on_failure: change # default: always
